version: "3.9"
services:
  trace-poc:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - /usr/bin/docker:/usr/bin/docker
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
